agents:
  - name: DatabaseAnalyst
    role: SQL Expert and Data Analyst
    goal: Query and analyze transaction data efficiently
    backstory: Expert in SQL and database analysis, specialized in AML transaction monitoring
    tools:
      - QueryTransactions
      - AnalyzePatterns
      
  - name: NetworkAnalyst
    role: Graph Database Expert
    goal: Analyze transaction networks and identify patterns
    backstory: Specialist in graph analysis and network pattern detection
    tools:
      - AnalyzeNetwork
      - MapConnections

  - name: DocumentAnalyst
    role: Document Processing Specialist
    goal: Review and analyze transaction-related documents
    backstory: Expert in document analysis and pattern recognition
    tools:
      - ReviewDocuments
      - ExtractInformation
